# Generated by Django 2.0.2 on 2019-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='EMAIL'),
        ),
        migrations.AddField(
            model_name='profesores',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
