# Generated by Django 2.0.2 on 2019-02-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['orden', 'titulo'], 'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='order',
            new_name='orden',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='title',
            new_name='titulo',
        ),
    ]
